dsn: "postgres://127.0.0.1/postgres?sslmode=disable&user=postgres&password=postgres"
password_hash_cost: 14
http_server:
  run_address: "127.0.0.1:8081"
  timeout: "5s"
  idle_timeout: "60s"
logger:
  log_path: "/var/log/gophermart/loyalty/app.log"
  level: "debug"
  max_size_mb: 5
  max_backups: 10
  max_age_days: 14
jwt:
  signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
  expiration: "24h"
migrations_path: "."
